#windowrule = idleinhibit always, class:xfce4-terminal

#(Instead you can do hyprctl dispatch inhibitidle on)


exec = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE


plugin {
    hyprsplit {
        num_workspaces = 6
    }
}

env = XDG_CURRENT_DESKTOP,Hyprland #new
env = LIBVA_DRIVER_NAME,radeonsi
env = NIXOS_OZONE_WL,1
env = MOZ_DISABLE_RDD_SANDBOX,1
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_WEBRENDER,1



cursor {
    no_hardware_cursors = true
}



