# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/e93ea29c-a013-432e-867c-c8a62a39a7a9";
#      fsType = "btrfs";
#      options = [ "subvol=@" ];
#    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/e93ea29c-a013-432e-867c-c8a62a39a7a9";
#      fsType = "btrfs";
#      options = [ "subvol=@home" ];
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/B861-2802";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b09d115-8ce5-4a23-b79a-50884dbcead7";
      fsType = "xfs";
      options = [ "noatime" ];
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2791-A03A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/e8ab554f-e75d-4a58-9cce-7a655a25cb64"; }
    ];



#  swapDevices =
#    [ { device = "/dev/disk/by-uuid/dac1663e-d2e2-4165-8514-8c4366e7dbc7"; }
#    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
