monitorv2 {
    output = DP-1
    mode = 5120x1440@144
    #mode = 2560x1440@144
    position = 0x0
    scale = 1
    bitdepth = 10
    vrr = 0


    # Color & HDR settings
    #cm = hdredid
    cm = dcip3
    sdrbrightness = 1.1
    sdrsaturation = 1.15

    supports_hdr = 1
    supports_wide_color = 1
    sdr_min_luminance = 0.005
    sdr_max_luminance = 200
    max_luminance = 1000
}

debug:disable_logs = false


bind = Super, I, pin


monitor=DP-2,1024x600@59.82,2010x1440,1.0
